services:
  criptconnect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: criptconnect-demo
    ports:
      - "3333:80"
    restart: unless-stopped
    labels:
      - "com.docker.description=CriptConnect Demo App"
